compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

enableProgressBars: false

logFilters:
  - code: YN0013
    level: discard

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.9.1.cjs
