// Copyright 2017-2026 @pezkuwi/extension-compat-metamask authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @pezkuwi/dev

export const packageInfo = { name: '@pezkuwi/extension-compat-metamask', path: 'auto', type: 'auto', version: '0.62.16' };
