// Copyright 2017-2026 @pezkuwi/extension-chains authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @pezkuwi/dev
// (packageInfo imports will be kept as-is, user-editable)

import { packageInfo as injectInfo } from '@pezkuwi/extension-inject/packageInfo';
import { detectPackage } from '@pezkuwi/util';

import { packageInfo } from './packageInfo.js';

detectPackage(packageInfo, null, [injectInfo]);
